### ISSUE TITLE
bcrypt issue on login

### ISSUE THREAD

**Issue by jsyadav1996** [ArjunAranetaCodes/nodejs-mysql-login-register#1]
i can register the user, but when i try to login i get error like below.
C:\login-signup-arjun\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^
Not a valid BCrypt hash.
Please help me with this.
Thanks

**Comment by jsyadav1996** [comment]
i fixed it.
I just changed the password data type column from varchar to text in user table and it worked.

**Comment by ArjunAranetaCodes** [comment]
I'm glad you made it work. I was just looking for the cause.
